builder:
  track: dev

labels:
  app-group: estafette-various
  team: estafette-team
  language: docker

stages:
  bake:
    image: extensions/docker:dev
    action: build
    container: hugo
    repositories:
    - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: hugo
    repositories:
    - estafette
    tags:
    - ${ESTAFETTE_GIT_BRANCH}