builder:
  track: dev

labels:
  app-group: estafette-various
  team: estafette-team
  language: docker

stages:
  bake:
    image: extensions/docker:dev
    action: build
    container: hugo
    repositories:
    - estafette

  check-container:
    parallelStages:
      check-efficiency:
        image: extensions/docker:dev
        action: dive
        container: hugo
        repositories:
        - estafette

      vulnerability-scan:
        image: extensions/docker:dev
        action: trivy
        container: hugo
        repositories:
        - estafette

  push-to-docker-hub:
    image: extensions/docker:dev
    action: push
    container: hugo
    repositories:
    - estafette
    tags:
    - ${ESTAFETTE_GIT_BRANCH}